apiVersion: v1
kind: Service
metadata:
  name: etcd-clusterapi-svc
  namespace: kube-cluster
  labels:
    app: etcd
spec:
  ports:
  - port: 2379
    name: etcd
    targetPort: 2379
  selector:
    app: etcd
