apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: machine-api-operator
  namespace: openshift-cluster-api
  labels:
    k8s-app: machine-api-operator
    managed-by-channel-operator: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: machine-api-operator
  template:
    metadata:
      labels:
        k8s-app: machine-api-operator
        tectonic-app-version-name: machine-api
    spec:
      containers:
      - name: machine-api-operator
        image: docker.io/openshift/origin-machine-api-operator:v4.0.0
        command:
        - "/machine-api-operator"
        args:
        - "start"
        - "--images-json=/etc/mao-config/images/images.json"
        resources:
          limits:
            cpu: 20m
            memory: 50Mi
          requests:
            cpu: 20m
            memory: 50Mi
        volumeMounts:
        - name: images
          mountPath: /etc/mao-config/images
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: images
        configMap:
                name: machine-api-operator-images
