apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  name: mao-trusted-ca
  namespace: openshift-machine-api
